kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-creator
  annotations:
    nomos.dev/cluster-selector: selector-env-dev
rules:
- apiGroups: ["batch/v1"]
  resources: ["jobs"]
  verbs:
   - "*"

